import { withAuthorization } from "@/modules/auth/withAuthorization"
import { ClientsPage } from "./ClientsPage"
import { clientAPI } from "@/modules/api"
import { FetcherOptions } from "@/shared/interfaces"

export const metadata = {
  title: "ClientX - My Clients",
  description: "Generated by create next app",
}

const getClients = async ({ accessToken }: FetcherOptions) => {
  return await clientAPI.get('/v1/clients', { accessToken })
}

export default () => withAuthorization(ClientsPage, getClients)
