import { withAuthorization } from "@/modules/auth/withAuthorization"
import { ClientsPage } from "./ClientsPage"

export const metadata = {
  title: "ClientX - My Clients",
  description: "Generated by create next app",
}

export default () => withAuthorization(ClientsPage)
