import { withAuthorization } from "@/modules/auth/withAuthorization"
import { ClientProfilePage } from "./ClientProfilePage"
import { getServerAuthSession } from "@/modules/auth/auth.utils"
import { clientAPI } from "@/modules/api"

export const metadata = {
  title: "ClientX - Client Profile",
  description: "Generated by create next app",
}

const getProfile = async (id: string) => {
  const session = getServerAuthSession()

  if (!session) {
    return null
  }

  return await clientAPI.get('/v1/clients/' + id, { accessToken: session.accessToken })
}

const PrivatePage = ({ params: { id } }: any) => withAuthorization(
  ClientProfilePage,
  async () => getProfile(id)
)
export default PrivatePage
