import { withAuthorization } from "@/modules/auth/withAuthorization"
import { BillingPage } from "./BillingPage"

export const metadata = {
  title: "ClientX - Client Profile",
  description: "Generated by create next app",
}

const PrivatePage = () => withAuthorization(BillingPage)
export default PrivatePage
