import { withAuthorization } from "@/modules/auth/withAuthorization"
import { DashboardPage } from "./DashboardPage"

export const metadata = {
  title: "ClientX - Dashboard",
  description: "Generated by create next app",
}

const PrivatePage = () => withAuthorization(DashboardPage)
export default PrivatePage
